config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/buy', to: 'users#buy'

  namespace :admin do
    resources :users, only: [:show, :new, :create]
    resources :rewards, only: [:index, :new, :create, :edit, :update, :destroy]
    patch 'manage-points', to: 'users#manage_points'
  end

  resources :rewards, only: [:index]
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :user_rewards, dependent: :destroy
  has_many :users, through: :user_rewards

  validates :name, presence: true, uniqueness: true
  validates :cost, presence: true

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
  has_many :user_rewards
  has_many :rewards, through: :user_rewards

  enum role: %w(user admin)
end

app/models/user_reward.rb
class UserReward < ActiveRecord::Base
  belongs_to :reward
  belongs_to :user
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: 'public/404' unless  current_admin?
  end

end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  def index
    @rewards = Reward.all
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      redirect_to admin_rewards_path
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update_attributes(reward_params)
      flash[:success] = "Reward updated"
      redirect_to admin_rewards_path
    else
      render 'edit'
    end
  end

  def destroy
    Reward.find(params[:id]).destroy
    flash.now[:notice] = "Reward deleted"
    render 'index'
  end

  private
    def reward_params
      params.require(:reward).permit(:name, :cost, :picture)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def show
    @users = User.all.where(role: 0)
    # byebug
    @usernames = User.all.where(role: 0).pluck(:username, :id)
  end

  def manage_points
    user = User.find(params[:point_manager][:user_id])

    new_points = user.points + params[:point_manager][:points].to_i
    user.update_attribute(:points, new_points)
    # byebug
    redirect_to admin_user_path(current_user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(current_user)
    else
      render :new
    end
  end

  private
    # def user_params
    #   params.require(:point_manager).permit(:points, :user_id)
    # end

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = Reward.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:info] = "Welcome back, #{user.username}"
      if current_user.admin?
        redirect_to admin_user_path(current_user)
      else
        redirect_to current_user
      end
    else
      flash[:error] = "Username or password are incorrect"
      render :new
    end
  end

  def destroy
    user = current_user
    session.clear
    flash[:notice] = "Goodbye, #{user.username}"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome #{@user.username}"
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @rewards = @user.rewards
    if @user != current_user
      flash[:notice] = "Stay on your own page, bro!"
      redirect_to user_path(current_user)
    end
  end

  def buy
    reward = Reward.find(params[:reward_id])
    if user_has_enough_points_to_buy?(reward)
      current_user.rewards << reward
      available_points = current_user.points - reward.cost
      redeemed_points = current_user.redeemed_points + reward.cost
      current_user.update_attributes(points: available_points, redeemed_points: redeemed_points)
      redirect_to current_user
    else
      flash[:error] = "You do not have enough points to buy that"
      redirect_to rewards_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

    def user_has_enough_points_to_buy?(reward)
      user = current_user
      (user.points - reward.cost) >= 0
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/rewards/_reward.html.erb
<div id="reward-<%= reward.id %>">
  <%= reward.name %>: <%= pluralize reward.cost, 'point' %>
  <%= image_tag reward.picture.url %>
  <%= link_to "Edit Reward", edit_admin_reward_path(reward) %>
  <%= link_to "Delete Reward", admin_reward_path(reward), method: :delete %>
</div>

app/views/admin/rewards/_reward_form.html.erb
<%= form_for([:admin, @reward]) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <br>
  <%= f.file_field :picture %>
  <br>
  <%= f.submit yield(:button) %>
<% end %>

app/views/admin/rewards/edit.html.erb
<%= provide(:button, "Update Reward") %>
<%= render 'reward_form' %>

app/views/admin/rewards/index.html.erb
<%= link_to "New Reward", new_admin_reward_path %>
<%= render @rewards if @rewards %>

app/views/admin/rewards/new.html.erb
<%= provide(:button, "Create Reward") %>
<%= render 'reward_form' %>

app/views/admin/users/new.html.erb
<h1>Account Registration</h1>
<%= form_for [:admin, @user] do |f|%>

  <%=  render 'shared/error_messages', object: f.object %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Create user" %>
<% end %>

app/views/admin/users/show.html.erb
Welcome, <%= current_user.username %>

<%= link_to "Create new user", new_admin_user_path %>
<%= link_to "Create new reward", new_admin_reward_path %>

<%= link_to "View Rewards", admin_rewards_path %>
<%= link_to "Logout", logout_path, method: :delete %>

<%= form_for(:point_manager, url: "/admin/manage-points", method: :patch) do |f| %>
    <%= f.select :user_id, @usernames  %>

    <%= f.label :points %>
    <%= f.number_field :points %>

    <%= f.submit "Modify Points"%>
<% end %>

<% @users.each do |user| %>

  <h2><%= user.username %></h2>
  <%= pluralize user.points, "point" %>
  <%= pluralize user.redeemed_points, "redeemed point" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PointBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |type, message| %>
    <%= content_tag :div, message, id: "flash_#{type}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/rewards/_reward.html.erb
<div id="reward-<%= reward.id %>">
  <%= reward.name %>: <%= pluralize reward.cost, 'point' %>
  <%= link_to "Buy", buy_path(reward_id: reward.id) %>
  <%= image_tag reward.picture.url %>
</div>

app/views/rewards/index.html.erb
<%= render @rewards %>
<%= link_to "Home", current_user %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div class="errors">
  The form contains <%= pluralize object.errors.count, 'error' %>:
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <%= content_tag :li, msg %>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/_user_rewards.html.erb
<% @rewards.each do |reward| %>
  <div id="reward-<%= reward.id %>">
    <%= reward.name %>
    <%= image_tag reward.picture.url %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Account Registration</h1>
<%= form_for @user do |f|%>

  <%=  render 'shared/error_messages', object: f.object %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<h1> <%= current_user.username %>'s Dashboard </h1>
<h2> <%= pluralize current_user.points, 'point' %> </h2>
<h2><%= pluralize current_user.rewards.count, 'reward' %> </h2>
<br>
<h2>Your Rewards:</h2>
<%= render 'user_rewards' %>
<%= link_to "Logout", logout_path, method: :delete %>
<%= link_to "Redeem points", rewards_path %>